language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.gradle

script:
  - cd lib
  - ./gradlew devtools:test --info
  - ./gradlew devtools-reduks:test --info
  - ./gradlew devtools-redux-kotlin:test --info
