language: android

android:
  components:
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - android-sdk-license-.+

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.gradle

before_script:

script:
  - ./gradlew :lib:devtools:build
