language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.gradle

before_script:
  - cd lib

script:
  - ./gradlew :devtools:test --info
  - ./gradlew :devtools-reduks:test --info
  - ./gradlew :devtools-redux-kotlin:test --info
